"""ORM models. Importing this module registers all tables on Base.metadata."""
from app.models.orm import (  # noqa: F401
    AltDocument,
    Asset,
    AssetPrice,
    Climatology,
    CommodityForecast,
    ContractFairValue,
    ContractPrice,
    ContractSpec,
    DailyBrief,
    FeaturesDaily,
    Forecast,
    ForecastRevision,
    FundamentalSeries,
    Location,
    ModelRun,
    ProbabilitySnapshot,
    RawClimateDriver,
    RawWeather,
    RawWeatherForecast,
    RevisionPrediction,
    SignalLog,
    TradingSignal,
)
